# crops.py

CROPS_DATA = {
    "wheat": "A rabi crop grown in winter, primarily in temperate regions.",
    "rice": "A kharif crop requiring high water, a staple food for a large part of the world's population.",
    "maize": "A versatile cereal used as food and fodder, widely grown across the globe.",
    "barley": "A hardy cereal used for animal feed, malting for beer, and in various food products.",
    "soybean": "A legume valued for its edible oil and high protein content, used in many food products.",
    "cotton": "A fiber crop and one of the most important cash crops, providing the raw material for textiles.",
    "sugarcane": "A tall, perennial grass used primarily for sugar production, and also for biofuel.",
    "potatoes": "A starchy root vegetable, a major food source globally and cultivated year-round in various climates.",
    "tomatoes": "A fruit (botanically) but used as a vegetable, a key ingredient in many cuisines.",
    "onions": "A bulb vegetable used as a staple in cooking worldwide for their pungent flavor.",
    "chickpeas": "A legume with high protein and fiber content, used in many dishes like hummus.",
    "lentils": "An edible legume, a good source of protein, and cooks relatively quickly.",
    "peanuts": "A legume grown mainly for its edible oil and protein-rich seeds.",
    "millet": "A group of small-seeded grasses widely grown around the world for food and fodder.",
    "sunflower": "An oilseed crop, mainly grown for its edible oil and seeds for snacking.",
    "coffee": "A plant whose beans are roasted to make the popular beverage, a significant cash crop.",
    "tea": "An aromatic beverage prepared from the leaves of the tea plant, a major global commodity.",
    "apples": "A widely cultivated fruit from the rose family, known for its crisp texture and sweet flavor.",
    "bananas": "An elongated, edible fruit produced by several kinds of large herbaceous flowering plants.",
    "oranges": "A citrus fruit known for its high vitamin C content and sweet, juicy pulp.",
    "grapes": "A fruit that grows in clusters, used for making wine, juice, and eaten fresh as table grapes.",
    "mangoes": "A stone fruit from tropical regions, known for its sweet, aromatic flesh.",
    "coconuts": "A fruit of the coconut palm, with a hard shell, white flesh, and a milky liquid.",
    "pineapples": "A tropical fruit with a tough, spiky exterior and sweet, juicy yellow flesh.",
    "strawberries": "A widely grown hybrid species of the genus Fragaria, cultivated for its sweet, red fruit.",
    "carrots": "A root vegetable, usually orange in color, rich in beta-carotene.",
    "spinach": "A leafy green vegetable, a good source of iron and vitamins.",
    "broccoli": "An edible green plant in the cabbage family, whose large flowering head is eaten as a vegetable.",
    "cauliflower": "A cruciferous vegetable with a large white head of florets.",
    "cabbage": "A leafy green or purple biennial plant, grown as an annual vegetable crop.",
    "lettuce": "A leafy vegetable used as the foundation of many salads.",
    "cucumbers": "A widely cultivated plant in the gourd family, with a cylindrical green fruit.",
    "peppers": "Fruits of the Capsicum plant, ranging from sweet bell peppers to hot chili peppers.",
    "garlic": "A species in the onion genus, known for its strong, pungent flavor.",
    "ginger": "A flowering plant whose rhizome is widely used as a spice and folk medicine.",
    "turmeric": "A flowering plant whose root is used as a spice, a key ingredient in many curries.",
    "cardamom": "A spice made from the seeds of several plants in the ginger family.",
    "cloves": "A spice made from the dried flower buds of a tree in the myrtle family.",
    "cinnamon": "A spice obtained from the inner bark of several tree species.",
    "nutmeg": "A spice made from the seed of the nutmeg tree.",
    "mustard": "A plant whose seeds are used to make the condiment, and its leaves are eaten as a vegetable.",
    "cumin": "A flowering plant in the family Apiaceae, whose seeds are used as a spice.",
    "coriander": "A plant whose seeds and leaves (cilantro) are used as a spice and herb.",
    "fennel": "A flowering plant species in the carrot family, with a distinctive anise-like flavor.",
    "sesame": "A flowering plant in the genus Sesamum, whose seeds are used for oil and as a spice.",
    "saffron": "A spice derived from the flower of Crocus sativus, known for its vibrant color and flavor.",
    "jute": "A long, soft, shiny bast fiber that can be spun into coarse, strong threads.",
    "rubber": "A natural polymer of isoprene, obtained from the latex of the rubber tree.",
    "cocoa": "The plant whose seeds (cacao beans) are used to make chocolate and cocoa powder.",
    "cashews": "A nut with a kidney shape, a popular snack and ingredient in cooking.",
    "almonds": "A tree nut rich in healthy fats, protein, and magnesium.",
    "pistachios": "A small tree nut in the cashew family, with a distinctive green color.",
    "walnuts": "A tree nut known for its brain-like shape and healthy omega-3 fatty acids.",
    "dates": "A sweet, edible fruit of the date palm.",
    "figs": "A fruit from the fig tree, known for its unique texture and sweetness.",
    "pomegranates": "A fruit with a tough outer rind and hundreds of red, juicy seeds.",
    "kiwi": "A small fruit with a fuzzy brown skin and bright green flesh.",
    "avocados": "A fruit with a large seed and creamy, green flesh.",
    "cherries": "A small, round stone fruit that is typically red or dark red.",
    "peaches": "A fuzzy-skinned stone fruit with sweet, juicy yellow or white flesh.",
    "plums": "A stone fruit with a smooth skin and a sweet or tart flavor.",
    "apricots": "A small, orange-colored stone fruit, similar to a peach.",
    "blueberries": "A small, edible berry with a blue or purple hue.",
    "raspberries": "An edible fruit from the rose family, composed of many drupelets.",
    "blackberries": "A widely cultivated berry that is a member of the genus Rubus.",
    "cranberries": "A low, creeping shrub with edible, red berries."
}