# soil.py

SOIL_DATA = {
    "delhi": {"soil_type": "Alluvial", "ph": 7.0},
    "mumbai": {"soil_type": "Black", "ph": 7.5},
    "kolkata": {"soil_type": "Alluvial", "ph": 6.8},
    "chennai": {"soil_type": "Red and Yellow", "ph": 6.0},
    "bengaluru": {"soil_type": "Red and Yellow", "ph": 6.2},
    "hyderabad": {"soil_type": "Black", "ph": 7.2},
    "ahmedabad": {"soil_type": "Alluvial", "ph": 7.1},
    "pune": {"soil_type": "Black", "ph": 7.4},
    "jaipur": {"soil_type": "Desert", "ph": 8.0},
    "lucknow": {"soil_type": "Alluvial", "ph": 6.9},
    "patna": {"soil_type": "Alluvial", "ph": 6.7},
    "bhopal": {"soil_type": "Black", "ph": 7.6},
    "bhubaneswar": {"soil_type": "Laterite", "ph": 5.5},
    "kochi": {"soil_type": "Laterite", "ph": 5.8},
    "guwahati": {"soil_type": "Alluvial", "ph": 6.5},
    "shimla": {"soil_type": "Forest", "ph": 5.0},
    "dehradun": {"soil_type": "Forest", "ph": 5.3},
    "chandigarh": {"soil_type": "Alluvial", "ph": 7.0},
    "agartala": {"soil_type": "Laterite", "ph": 5.6},
    "gandhinagar": {"soil_type": "Alluvial", "ph": 7.0},
    "indore": {"soil_type": "Black", "ph": 7.5},
    "kozhikode": {"soil_type": "Laterite", "ph": 5.9},
    "nagpur": {"soil_type": "Black", "ph": 7.3},
    "ranchi": {"soil_type": "Laterite", "ph": 5.7},
    "shillong": {"soil_type": "Laterite", "ph": 5.4},
    "srinagar": {"soil_type": "Alluvial", "ph": 6.6},
    "thiruvananthapuram": {"soil_type": "Laterite", "ph": 5.8},
    "amritsar": {"soil_type": "Alluvial", "ph": 7.2},
    "jodhpur": {"soil_type": "Desert", "ph": 8.1},
    "vadodara": {"soil_type": "Alluvial", "ph": 7.0},
    "visakhapatnam": {"soil_type": "Red and Yellow", "ph": 6.1},
    "vijayawada": {"soil_type": "Alluvial", "ph": 6.9},
    "udaipur": {"soil_type": "Red and Yellow", "ph": 6.3},
    "kanpur": {"soil_type": "Alluvial", "ph": 6.8},
    "gwalior": {"soil_type": "Alluvial", "ph": 7.1},
    "rajkot": {"soil_type": "Black", "ph": 7.4},
    "aligarh": {"soil_type": "Alluvial", "ph": 7.0},
    "nashik": {"soil_type": "Black", "ph": 7.6},
    "surat": {"soil_type": "Alluvial", "ph": 7.2},
    "ludhiana": {"soil_type": "Alluvial", "ph": 7.1},
    "mysuru": {"soil_type": "Red and Yellow", "ph": 6.4},
    "erode": {"soil_type": "Red and Yellow", "ph": 6.0},
    "agra": {"soil_type": "Alluvial", "ph": 7.0},
    "allahabad": {"soil_type": "Alluvial", "ph": 6.9},
    "varanasi": {"soil_type": "Alluvial", "ph": 6.8},
    "coimbatore": {"soil_type": "Red and Black", "ph": 6.5},
    "madurai": {"soil_type": "Red and Black", "ph": 6.6},
    "kolhapur": {"soil_type": "Black", "ph": 7.5},
    "jabalpur": {"soil_type": "Black", "ph": 7.4},
    "aurangabad": {"soil_type": "Black", "ph": 7.3},
    "amravati": {"soil_type": "Black", "ph": 7.5},
    "goa": {"soil_type": "Laterite", "ph": 5.5},
    "gwalior": {"soil_type": "Alluvial", "ph": 7.1},
    "udaipur": {"soil_type": "Red and Yellow", "ph": 6.3},
    "noida": {"soil_type": "Alluvial", "ph": 7.0},
    "ghaziabad": {"soil_type": "Alluvial", "ph": 7.1},
    "faridabad": {"soil_type": "Alluvial", "ph": 7.0},
    "gurgaon": {"soil_type": "Alluvial", "ph": 7.0},
    "bikaner": {"soil_type": "Desert", "ph": 8.2},
    "gaya": {"soil_type": "Alluvial", "ph": 6.7},
    "dhanbad": {"soil_type": "Laterite", "ph": 5.6},
    "jamshedpur": {"soil_type": "Laterite", "ph": 5.7},
    "bilaspur": {"soil_type": "Laterite", "ph": 5.8},
    "raipur": {"soil_type": "Red and Yellow", "ph": 6.2},
    "salem": {"soil_type": "Red and Yellow", "ph": 6.1},
    "tiruchirappalli": {"soil_type": "Alluvial", "ph": 6.9},
    "vellore": {"soil_type": "Red and Yellow", "ph": 6.3},
    "mangalore": {"soil_type": "Laterite", "ph": 5.9},
    "hubballi": {"soil_type": "Black", "ph": 7.3},
    "belgaum": {"soil_type": "Black", "ph": 7.4},
    "kakinada": {"soil_type": "Alluvial", "ph": 6.8},
    "tirupati": {"soil_type": "Red and Yellow", "ph": 6.2},
    "nellore": {"soil_type": "Alluvial", "ph": 7.0},
    "rajahmundry": {"soil_type": "Alluvial", "ph": 6.9},
    "panaji": {"soil_type": "Laterite", "ph": 5.6},
    "gangtok": {"soil_type": "Forest", "ph": 5.1},
    "aizawl": {"soil_type": "Forest", "ph": 5.2},
    "kohima": {"soil_type": "Forest", "ph": 5.3},
    "imphal": {"soil_type": "Laterite", "ph": 5.4},
    "itanagar": {"soil_type": "Forest", "ph": 5.0},
    "port blair": {"soil_type": "Laterite", "ph": 5.7},
    "pondicherry": {"soil_type": "Alluvial", "ph": 6.9},
    "bhavnagar": {"soil_type": "Black", "ph": 7.5},
    "jamnagar": {"soil_type": "Black", "ph": 7.4},
    "junagadh": {"soil_type": "Black", "ph": 7.5},
    "bhuj": {"soil_type": "Desert", "ph": 8.1},
    "amreli": {"soil_type": "Black", "ph": 7.4},
    "porbandar": {"soil_type": "Alluvial", "ph": 7.2},
    "barmer": {"soil_type": "Desert", "ph": 8.3},
    "jaipur": {"soil_type": "Desert", "ph": 8.0},
    "jaisalmer": {"soil_type": "Desert", "ph": 8.4},
    "bhiwani": {"soil_type": "Desert", "ph": 7.9},
    "hisar": {"soil_type": "Alluvial", "ph": 7.3},
    "rohtak": {"soil_type": "Alluvial", "ph": 7.1},
    "panipat": {"soil_type": "Alluvial", "ph": 7.0},
    "karnal": {"soil_type": "Alluvial", "ph": 7.2},
    "yamunanagar": {"soil_type": "Alluvial", "ph": 7.1},
    "amritsar": {"soil_type": "Alluvial", "ph": 7.2},
    "jalandhar": {"soil_type": "Alluvial", "ph": 7.0},
    "patiala": {"soil_type": "Alluvial", "ph": 7.1},
    "ludhiana": {"soil_type": "Alluvial", "ph": 7.1},
    "chandigarh": {"soil_type": "Alluvial", "ph": 7.0},
    "firozpur": {"soil_type": "Alluvial", "ph": 7.2},
    "bathinda": {"soil_type": "Alluvial", "ph": 7.3},
    "moga": {"soil_type": "Alluvial", "ph": 7.1},
    "mohali": {"soil_type": "Alluvial", "ph": 7.0},
    "shimla": {"soil_type": "Forest", "ph": 5.0},
    "solan": {"soil_type": "Forest", "ph": 5.2},
    "mandi": {"soil_type": "Forest", "ph": 5.1},
    "kullu": {"soil_type": "Forest", "ph": 5.0},
    "dharamsala": {"soil_type": "Forest", "ph": 5.3},
    "jabalpur": {"soil_type": "Black", "ph": 7.4},
    "ujjain": {"soil_type": "Black", "ph": 7.5},
    "sagar": {"soil_type": "Black", "ph": 7.3},
    "rewa": {"soil_type": "Alluvial", "ph": 6.8},
    "satna": {"soil_type": "Alluvial", "ph": 6.7},
    "katni": {"soil_type": "Alluvial", "ph": 6.9},
    "burhanpur": {"soil_type": "Black", "ph": 7.6},
    "gwalior": {"soil_type": "Alluvial", "ph": 7.1},
    "nagpur": {"soil_type": "Black", "ph": 7.3},
    "nashik": {"soil_type": "Black", "ph": 7.6},
    "pune": {"soil_type": "Black", "ph": 7.4},
    "aurangabad": {"soil_type": "Black", "ph": 7.3},
    "akola": {"soil_type": "Black", "ph": 7.5},
    "amravati": {"soil_type": "Black", "ph": 7.5},
    "solapur": {"soil_type": "Black", "ph": 7.4},
    "kolhapur": {"soil_type": "Black", "ph": 7.5},
    "chandrapur": {"soil_type": "Black", "ph": 7.2},
    "gondia": {"soil_type": "Black", "ph": 7.3},
    "jalgaon": {"soil_type": "Black", "ph": 7.5},
    "osmanabad": {"soil_type": "Black", "ph": 7.4},
    "latur": {"soil_type": "Black", "ph": 7.6},
    "nanded": {"soil_type": "Black", "ph": 7.3},
    "yavatmal": {"soil_type": "Black", "ph": 7.4},
    "wardha": {"soil_type": "Black", "ph": 7.5},
    "bhubaneswar": {"soil_type": "Laterite", "ph": 5.5},
    "cuttack": {"soil_type": "Alluvial", "ph": 6.8},
    "berhampur": {"soil_type": "Red and Yellow", "ph": 6.0},
    "rourkela": {"soil_type": "Laterite", "ph": 5.7},
    "sambalpur": {"soil_type": "Alluvial", "ph": 6.9},
    "puri": {"soil_type": "Laterite", "ph": 5.6},
    "dhenkanal": {"soil_type": "Laterite", "ph": 5.5},
    "jamshedpur": {"soil_type": "Laterite", "ph": 5.7},
    "ranchi": {"soil_type": "Laterite", "ph": 5.7},
    "dhanbad": {"soil_type": "Laterite", "ph": 5.6},
    "bokaro": {"soil_type": "Laterite", "ph": 5.8},
    "hazaribagh": {"soil_type": "Laterite", "ph": 5.5},
    "patna": {"soil_type": "Alluvial", "ph": 6.7},
    "gaya": {"soil_type": "Alluvial", "ph": 6.7},
    "muzaffarpur": {"soil_type": "Alluvial", "ph": 6.8},
    "bhagalpur": {"soil_type": "Alluvial", "ph": 6.9},
    "darbhanga": {"soil_type": "Alluvial", "ph": 6.6},
    "bihar sharif": {"soil_type": "Alluvial", "ph": 6.7},
    "purnia": {"soil_type": "Alluvial", "ph": 6.8},
    "siliguri": {"soil_type": "Alluvial", "ph": 6.5},
    "kolkata": {"soil_type": "Alluvial", "ph": 6.8},
    "howrah": {"soil_type": "Alluvial", "ph": 6.9},
    "durgapur": {"soil_type": "Alluvial", "ph": 6.7},
    "asansol": {"soil_type": "Alluvial", "ph": 6.8},
    "darjeeling": {"soil_type": "Forest", "ph": 5.2},
    "jalpaiguri": {"soil_type": "Laterite", "ph": 5.6},
    "cooch behar": {"soil_type": "Alluvial", "ph": 6.7},
    "guwahati": {"soil_type": "Alluvial", "ph": 6.5},
    "dibrugarh": {"soil_type": "Alluvial", "ph": 6.4},
    "silchar": {"soil_type": "Alluvial", "ph": 6.6},
    "jamshedpur": {"soil_type": "Laterite", "ph": 5.7},
    "ranchi": {"soil_type": "Laterite", "ph": 5.7},
    "dhanbad": {"soil_type": "Laterite", "ph": 5.6},
    "agra": {"soil_type": "Alluvial", "ph": 7.0},
    "allahabad": {"soil_type": "Alluvial", "ph": 6.9},
    "varanasi": {"soil_type": "Alluvial", "ph": 6.8},
    "kanpur": {"soil_type": "Alluvial", "ph": 6.8},
    "lucknow": {"soil_type": "Alluvial", "ph": 6.9},
    "meerut": {"soil_type": "Alluvial", "ph": 7.1},
    "ghaziabad": {"soil_type": "Alluvial", "ph": 7.1},
    "aligarh": {"soil_type": "Alluvial", "ph": 7.0},
    "bareilly": {"soil_type": "Alluvial", "ph": 6.9},
    "moradabad": {"soil_type": "Alluvial", "ph": 7.0},
    "saharanpur": {"soil_type": "Alluvial", "ph": 7.1},
    "gorakhpur": {"soil_type": "Alluvial", "ph": 6.8},
    "firozabad": {"soil_type": "Alluvial", "ph": 7.0},
    "jhansi": {"soil_type": "Alluvial", "ph": 7.2},
    "prayagraj": {"soil_type": "Alluvial", "ph": 6.9},
    "kollam": {"soil_type": "Laterite", "ph": 5.8},
    "kochi": {"soil_type": "Laterite", "ph": 5.8},
    "kozhikode": {"soil_type": "Laterite", "ph": 5.9},
    "thrissur": {"soil_type": "Laterite", "ph": 5.7},
    "kannur": {"soil_type": "Laterite", "ph": 5.8},
    "palakkad": {"soil_type": "Laterite", "ph": 5.9},
    "alappuzha": {"soil_type": "Alluvial", "ph": 6.5},
    "kottayam": {"soil_type": "Laterite", "ph": 5.8},
    "idukki": {"soil_type": "Laterite", "ph": 5.7},
    "kochi": {"soil_type": "Laterite", "ph": 5.8},
    "chennai": {"soil_type": "Red and Yellow", "ph": 6.0},
    "coimbatore": {"soil_type": "Red and Black", "ph": 6.5},
    "madurai": {"soil_type": "Red and Black", "ph": 6.6},
    "salem": {"soil_type": "Red and Yellow", "ph": 6.1},
    "erode": {"soil_type": "Red and Yellow", "ph": 6.0},
    "tirunelveli": {"soil_type": "Red and Yellow", "ph": 6.2},
    "tirupur": {"soil_type": "Red and Yellow", "ph": 6.1},
    "dindigul": {"soil_type": "Red and Yellow", "ph": 6.3},
    "thoothukudi": {"soil_type": "Alluvial", "ph": 6.9},
    "thanjavur": {"soil_type": "Alluvial", "ph": 6.8},
    "nagapattinam": {"soil_type": "Alluvial", "ph": 6.7},
    "kanyakumari": {"soil_type": "Laterite", "ph": 5.8},
    "bangalore": {"soil_type": "Red and Yellow", "ph": 6.2},
    "mysuru": {"soil_type": "Red and Yellow", "ph": 6.4},
    "mangalore": {"soil_type": "Laterite", "ph": 5.9},
    "hubballi": {"soil_type": "Black", "ph": 7.3},
    "belgaum": {"soil_type": "Black", "ph": 7.4},
    "dharwad": {"soil_type": "Black", "ph": 7.3},
    "kalaburagi": {"soil_type": "Black", "ph": 7.5},
    "bidar": {"soil_type": "Black", "ph": 7.4},
    "bijapur": {"soil_type": "Black", "ph": 7.6},
    "chitradurga": {"soil_type": "Red and Yellow", "ph": 6.1},
    "hassan": {"soil_type": "Laterite", "ph": 5.8},
    "shivamogga": {"soil_type": "Laterite", "ph": 5.9},
    "chikkamagaluru": {"soil_type": "Laterite", "ph": 5.7},
    "vijayawada": {"soil_type": "Alluvial", "ph": 6.9},
    "visakhapatnam": {"soil_type": "Red and Yellow", "ph": 6.1},
    "guntur": {"soil_type": "Alluvial", "ph": 6.8},
    "nellore": {"soil_type": "Alluvial", "ph": 7.0},
    "kurnool": {"soil_type": "Black", "ph": 7.5},
    "rajahmundry": {"soil_type": "Alluvial", "ph": 6.9},
    "tirupati": {"soil_type": "Red and Yellow", "ph": 6.2},
    "anamaluru": {"soil_type": "Red and Yellow", "ph": 6.0},
    "kadapa": {"soil_type": "Red and Yellow", "ph": 6.3},
    "machilipatnam": {"soil_type": "Alluvial", "ph": 7.0},
    "srikakulam": {"soil_type": "Alluvial", "ph": 6.8},
    "hyderabad": {"soil_type": "Black", "ph": 7.2},
    "warangal": {"soil_type": "Black", "ph": 7.3},
    "nizamabad": {"soil_type": "Black", "ph": 7.4},
    "karimnagar": {"soil_type": "Black", "ph": 7.2},
    "khammam": {"soil_type": "Black", "ph": 7.3},
    "nalgonda": {"soil_type": "Black", "ph": 7.4},
    "secunderabad": {"soil_type": "Black", "ph": 7.2},
    "adilabad": {"soil_type": "Black", "ph": 7.5},
    "raichur": {"soil_type": "Black", "ph": 7.5},
    "koppal": {"soil_type": "Black", "ph": 7.4},
    "gadag": {"soil_type": "Black", "ph": 7.5},
    "haveri": {"soil_type": "Black", "ph": 7.3},
    "uttara kannada": {"soil_type": "Laterite", "ph": 5.9},
    "dakshina kannada": {"soil_type": "Laterite", "ph": 5.8},
    "kasaragod": {"soil_type": "Laterite", "ph": 5.9},
    "malappuram": {"soil_type": "Laterite", "ph": 5.8},
    "kozhikode": {"soil_type": "Laterite", "ph": 5.9},
    "wayanad": {"soil_type": "Forest", "ph": 5.6},
    "palakkad": {"soil_type": "Laterite", "ph": 5.9},
    "thrissur": {"soil_type": "Laterite", "ph": 5.7},
    "alappuzha": {"soil_type": "Alluvial", "ph": 6.5},
    "kottayam": {"soil_type": "Laterite", "ph": 5.8},
    "idukki": {"soil_type": "Laterite", "ph": 5.7},
    "pathanamthitta": {"soil_type": "Laterite", "ph": 5.8},
    "kollam": {"soil_type": "Laterite", "ph": 5.8},
    "thiruvananthapuram": {"soil_type": "Laterite", "ph": 5.8},
    "nagercoil": {"soil_type": "Laterite", "ph": 5.7},
    "kanyakumari": {"soil_type": "Laterite", "ph": 5.8},
    "madurai": {"soil_type": "Red and Black", "ph": 6.6},
    "tirunelveli": {"soil_type": "Red and Yellow", "ph": 6.2},
    "thoothukudi": {"soil_type": "Alluvial", "ph": 6.9},
    "thanjavur": {"soil_type": "Alluvial", "ph": 6.8},
    "trichy": {"soil_type": "Alluvial", "ph": 6.9},
    "vellore": {"soil_type": "Red and Yellow", "ph": 6.3},
    "erode": {"soil_type": "Red and Yellow", "ph": 6.0},
    "salem": {"soil_type": "Red and Yellow", "ph": 6.1},
    "karur": {"soil_type": "Red and Yellow", "ph": 6.2},
    "perambalur": {"soil_type": "Red and Yellow", "ph": 6.3},
    "ariyalur": {"soil_type": "Red and Yellow", "ph": 6.2},
    "tiruvannamalai": {"soil_type": "Red and Yellow", "ph": 6.4},
    "dharmapuri": {"soil_type": "Red and Yellow", "ph": 6.3},
    "krishnagiri": {"soil_type": "Red and Yellow", "ph": 6.4},
    "namakkal": {"soil_type": "Red and Yellow", "ph": 6.2},
    "nilgiris": {"soil_type": "Laterite", "ph": 5.5},
    "coonoor": {"soil_type": "Laterite", "ph": 5.6},
    "ooty": {"soil_type": "Laterite", "ph": 5.5},
    "coimbatore": {"soil_type": "Red and Black", "ph": 6.5},
    "chennai": {"soil_type": "Red and Yellow", "ph": 6.0},
    "kodaikanal": {"soil_type": "Laterite", "ph": 5.7},
    "dindigul": {"soil_type": "Red and Yellow", "ph": 6.3},
    "sivaganga": {"soil_type": "Black", "ph": 7.4},
    "virudhunagar": {"soil_type": "Black", "ph": 7.5},
    "ramnad": {"soil_type": "Saline", "ph": 8.0},
    "pondy": {"soil_type": "Alluvial", "ph": 6.9},
    " Karaikal ": {"soil_type": "Alluvial", "ph": 6.8},
    "yanam": {"soil_type": "Alluvial", "ph": 6.9},
    "mahe": {"soil_type": "Laterite", "ph": 5.8},
    "port blair": {"soil_type": "Laterite", "ph": 5.7},
    "car nicobar": {"soil_type": "Laterite", "ph": 5.8},
    "aizawl": {"soil_type": "Forest", "ph": 5.2},
    "kohima": {"soil_type": "Forest", "ph": 5.3},
    "imphal": {"soil_type": "Laterite", "ph": 5.4},
    "itanagar": {"soil_type": "Forest", "ph": 5.0},
    "agartala": {"soil_type": "Laterite", "ph": 5.6},
    "gangtok": {"soil_type": "Forest", "ph": 5.1},
    "shillong": {"soil_type": "Laterite", "ph": 5.4},
    "srinagar": {"soil_type": "Alluvial", "ph": 6.6},
    "jammu": {"soil_type": "Alluvial", "ph": 6.7},
    "anantnag": {"soil_type": "Alluvial", "ph": 6.5},
    "pulwama": {"soil_type": "Alluvial", "ph": 6.6},
    "baramulla": {"soil_type": "Alluvial", "ph": 6.7},
    "ganderbal": {"soil_type": "Alluvial", "ph": 6.6},
    "le": {"soil_type": "Desert", "ph": 7.8},
    "kargil": {"soil_type": "Desert", "ph": 7.9},
    "port blair": {"soil_type": "Laterite", "ph": 5.7},
    "noida": {"soil_type": "Alluvial", "ph": 7.0},
    "gurgaon": {"soil_type": "Alluvial", "ph": 7.0},
    "pune": {"soil_type": "Black", "ph": 7.4},
    "mumbai": {"soil_type": "Black", "ph": 7.5},
    "bangalore": {"soil_type": "Red and Yellow", "ph": 6.2},
    "hyderabad": {"soil_type": "Black", "ph": 7.2},
    "ahmedabad": {"soil_type": "Alluvial", "ph": 7.1},
    "chennai": {"soil_type": "Red and Yellow", "ph": 6.0},
    "kolkata": {"soil_type": "Alluvial", "ph": 6.8},
    "delhi": {"soil_type": "Alluvial", "ph": 7.0},
    "jaipur": {"soil_type": "Desert", "ph": 8.0},
    "lucknow": {"soil_type": "Alluvial", "ph": 6.9},
    "nagpur": {"soil_type": "Black", "ph": 7.3},
    "kanpur": {"soil_type": "Alluvial", "ph": 6.8},
    "visakhapatnam": {"soil_type": "Red and Yellow", "ph": 6.1},
    "indore": {"soil_type": "Black", "ph": 7.5},
    "ludhiana": {"soil_type": "Alluvial", "ph": 7.1},
    "agra": {"soil_type": "Alluvial", "ph": 7.0},
    "bhopal": {"soil_type": "Black", "ph": 7.6},
    "meerut": {"soil_type": "Alluvial", "ph": 7.1},
    "rajkot": {"soil_type": "Black", "ph": 7.4},
    "kollam": {"soil_type": "Laterite", "ph": 5.8},
    "bhuj": {"soil_type": "Desert", "ph": 8.1},
    "solapur": {"soil_type": "Black", "ph": 7.4},
    "surat": {"soil_type": "Alluvial", "ph": 7.2},
    "hubballi": {"soil_type": "Black", "ph": 7.3},
    "patna": {"soil_type": "Alluvial", "ph": 6.7},
    "gaya": {"soil_type": "Alluvial", "ph": 6.7},
    "ranchi": {"soil_type": "Laterite", "ph": 5.7},
    "jamshedpur": {"soil_type": "Laterite", "ph": 5.7},
    "bhubaneswar": {"soil_type": "Laterite", "ph": 5.5},
    "udaipur": {"soil_type": "Red and Yellow", "ph": 6.3},
    "ghaziabad": {"soil_type": "Alluvial", "ph": 7.1},
    "faridabad": {"soil_type": "Alluvial", "ph": 7.0},
    "gwalior": {"soil_type": "Alluvial", "ph": 7.1},
    "allahabad": {"soil_type": "Alluvial", "ph": 6.9},
    "coimbatore": {"soil_type": "Red and Black", "ph": 6.5},
    "madurai": {"soil_type": "Red and Black", "ph": 6.6},
    "tiruchirappalli": {"soil_type": "Alluvial", "ph": 6.9},
    "guwahati": {"soil_type": "Alluvial", "ph": 6.5},
    "vadodara": {"soil_type": "Alluvial", "ph": 7.0},
    "varanasi": {"soil_type": "Alluvial", "ph": 6.8},
    "kochi": {"soil_type": "Laterite", "ph": 5.8},
    "puducherry": {"soil_type": "Alluvial", "ph": 6.9},
    "shillong": {"soil_type": "Laterite", "ph": 5.4},
    "srinagar": {"soil_type": "Alluvial", "ph": 6.6},
    "kohima": {"soil_type": "Forest", "ph": 5.3},
    "panaji": {"soil_type": "Laterite", "ph": 5.6},
    "jammu": {"soil_type": "Alluvial", "ph": 6.7},
    "port blair": {"soil_type": "Laterite", "ph": 5.7},
    "agartala": {"soil_type": "Laterite", "ph": 5.6},
    "gangtok": {"soil_type": "Forest", "ph": 5.1},
    "aizawl": {"soil_type": "Forest", "ph": 5.2},
    "itanagar": {"soil_type": "Forest", "ph": 5.0},
    "imphal": {"soil_type": "Laterite", "ph": 5.4}
}